import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, ArrowRight } from "lucide-react";
import { bookingHref, site } from "@/lib/site";
import "./capabilities.css";

export const metadata: Metadata = {
  title: "AI Implementation & Workflow Demonstrations | Archangel",
  description: "Explore three working, synthetic demonstrations of business workflow redesign, AI application engineering and human-controlled automation. Bangkok-based founder-led implementation.",
  alternates: {canonical:"/capabilities"},
};
const demonstrations = [
  {n:"01",area:"FINANCE OPERATIONS",name:"Accounts payable",line:"Turn invoices into a reviewed payment-ready batch.",description:"Match invoices to POs and receipts. Detect duplicates, amount and quantity discrepancies, and supplier bank changes. Show every rule, human override and audit event.", audience:"CFO · Finance director · AP lead",href:"/capabilities/ap.html",flow:"INVOICES → MATCHING → EXCEPTIONS → APPROVAL → EXPORT"},
  {n:"02",area:"REVENUE OPERATIONS",name:"Sales operations",line:"Make every worthwhile enquiry accountable.",description:"Merge incoming enquiries, score transparent buying signals, match accounts, draft for review, assign owners and follow-ups, and update a sample CRM pipeline.",audience:"CEO · COO · Commercial director",href:"/capabilities/sales.html",flow:"ENQUIRIES → QUALIFY → REVIEW → CRM HANDOFF"},
  {n:"03",area:"CLINICAL PRODUCT ENGINEERING",name:"Hanna",line:"One consultation. A note and a care plan.",description:"A synthetic clinician workflow: consent, simulated recording, transcript, editable SOAP note, mandatory medication confirmation and care plans in five languages.",audience:"Healthcare operators · Clinical leads",href:"/capabilities/hanna.html",flow:"CONSULT → TRANSCRIPT → CLINICIAN REVIEW → PATIENT PLAN"},
];
export default function CapabilitiesPage(){return <main id="main-content" className="aa-home cap-page">
  <section className="cap-hero"><div className="page-shell"><div className="cap-supra"><span>ARCHANGEL / CAPABILITY SHOWCASE</span><span>FOUNDER-LED ENGINEERING · BANGKOK</span></div><div className="cap-hero-grid"><div><span className="cap-eyebrow">MAKE AI USEFUL AT WORK.</span><h1>Less work<br/>between <em>the work.</em></h1></div><div className="cap-hero-copy"><p>We identify expensive, repetitive work, redesign the process, build AI-powered systems and measure the improvement.</p><p>From finance and sales operations to custom software and healthcare products: we design the workflow, engineer the system and put people in control of important decisions.</p><Link href={bookingHref} className="aa-pill aa-pill-lime">Discuss your workflow <ArrowUpRight size={18}/></Link></div></div><div className="cap-hero-bottom"><span>DISCOVER → DESIGN → BUILD → DEPLOY → OPTIMISE</span><span>01 — 03 / EXPLORE BELOW ↓</span></div></div></section>
  <section className="cap-intro page-shell"><div><p className="cap-kicker">THE WORK WE TAKE ON</p><h2>Operational problems.<br/><em>Working software.</em></h2></div><div className="cap-intro-body"><p>Invoices queued for manual approval. Enquiries scattered across channels. Clinicians repeating documentation. Reports copied between spreadsheets. Exceptions sitting in somebody’s inbox.</p><p>We map inputs, decisions, permissions and system handoffs. Then we build process automation, AI-assisted applications, custom interfaces, integrations, audit trails and deployment controls—rather than leaving you with a slide deck or disconnected tools.</p></div></section>
  <section className="cap-lab"><div className="page-shell"><div className="cap-section-head"><div><p className="cap-kicker">INTERACTIVE / THREE FUNCTIONS</p><h2>Don’t imagine the workflow.<br/><em>Try it.</em></h2></div><p>Each demonstration is fully interactive and runs in your browser without sign-in. These are deterministic examples with synthetic data—not live AI, customer deployments or integration claims.</p></div><div className="cap-cards">{demonstrations.map(d=><article className="cap-card" key={d.n}><div className="cap-card-top"><span>{d.n} / {d.area}</span><span>FUNCTIONAL DEMO ↗</span></div><div className="cap-card-view"><span className="cap-terminal">ARCHANGEL / CAPABILITY LAB</span><span className="cap-view-stage">{d.n==='01'?'MATCHED / EXCEPTION / APPROVED':d.n==='02'?'ENQUIRY / OWNER / HANDOFF':'TRANSCRIPT / SOAP / PATIENT'}</span><div className="cap-view-bars"><i/><i/><i/></div><span className="cap-terminal">INPUT → DECISION → HUMAN → OUTPUT</span></div><div className="cap-card-body"><p className="cap-card-audience">{d.audience}</p><h3>{d.name}<span>.</span></h3><p className="cap-card-line">{d.line}</p><p className="cap-card-description">{d.description}</p><p className="cap-card-flow">{d.flow}</p><a className="cap-demo-link" href={d.href}>Open the interactive demo <ArrowUpRight size={17}/></a></div></article>)}</div><p className="cap-lab-note">Sample inputs, outputs and review decisions remain local to the browser. No records are sent or stored on Archangel systems.</p></div></section>
  <section className="cap-evidence page-shell"><div><p className="cap-kicker">PROOF OF ENGINEERING</p><h2>We build the system,<br/><em>not just the idea.</em></h2><p>Our own software and this public website show our approach to product design, technical delivery and usable interfaces. The demos above show operational architecture; they are not presented as customer case studies.</p></div><div className="cap-evidence-list"><div><span>01 / OWN PRODUCT · IN DEVELOPMENT</span><h3>Hanna Care Intelligence</h3><p>Codebase includes a consultation workflow, structured clinical note, medication review, multilingual patient documents, application routes and printable care-plan components. This is product-development evidence, not a claimed hospital deployment or clinical validation.</p><a href="https://www.hanna.care" target="_blank" rel="noreferrer">Explore the public product website ↗</a></div><div><span>02 / PUBLIC ENGINEERING · LIVE WEBSITE</span><h3>Archangel digital platform</h3><p>The website you are using is a working example of our responsive interface design, Next.js application engineering and content architecture.</p><Link href="/work">View selected work <ArrowRight size={16}/></Link></div><div><span>03 / IMPLEMENTATION · EXAMPLE WORKFLOWS</span><h3>Finance, sales and clinical systems</h3><p>Each sample demonstrates deterministic decision rules, review gates, workflow state, audit events and structured exports. Actual implementations are tailored to a client’s systems, controls and data.</p><a href="/capabilities/ap.html">Inspect the finance demo ↗</a></div></div></section>
  <section className="cap-process"><div className="page-shell"><p className="cap-kicker">HOW AN ENGAGEMENT STARTS</p><h2>From first conversation<br/>to a working release.</h2><div className="cap-process-grid"><div><span>01 / FREE · 15 MINUTES</span><h3>Discovery call</h3><p>Understand one business problem, its owner, volume, constraints and the desired outcome.</p></div><div><span>02 / THB 45,000 · 3 HOURS</span><h3>Transformation workshop</h3><p>Map the existing and proposed workflow, data inputs, human decisions, integration points, risks and an implementation scope.</p></div><div><span>03 / SCOPED PROPOSAL</span><h3>Implementation</h3><p>Design, build, test and deploy the agreed software, automation or AI application—with training and acceptance criteria.</p></div><div><span>04 / AGREED AFTER DEPLOYMENT</span><h3>Support & optimisation</h3><p>Monitor agreed measures, maintain integrations, resolve exceptions and improve the system as requirements change.</p></div></div></div></section>
  <section className="cap-cta"><div className="page-shell cap-cta-grid"><div><p className="cap-kicker">YOUR PROCESS / NEXT</p><h2>Which workflow should<br/>work <em>better?</em></h2></div><div><p>Show us one expensive handoff, repetitive decision or product idea. We’ll identify the smallest useful first milestone.</p><Link href={bookingHref} className="aa-pill aa-pill-lime">Book a free 15-minute call <ArrowUpRight size={18}/></Link><a className="cap-mail" href={`mailto:${site.email}`}>{site.email} ↗</a></div></div></section>
</main>}